# Generated by Django 4.0.5 on 2022-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='course_codes',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
