# Generated by Django 4.0.5 on 2022-07-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_room_code_remove_room_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='course_codes',
            field=models.CharField(default='', max_length=8),
        ),
    ]
