# Generated by Django 4.0.5 on 2022-07-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_course_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
