# Generated by Django 4.0.5 on 2022-07-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room2_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room2',
            name='code',
        ),
        migrations.RemoveField(
            model_name='room2',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='room2',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room2',
            name='votes_to_skip',
        ),
        migrations.AddField(
            model_name='room2',
            name='course_codes',
            field=models.CharField(default='', max_length=8),
        ),
    ]
