# Generated by Django 4.0.5 on 2022-07-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_room2_code_remove_room2_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room2',
            name='course_codes',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
