# Generated by Django 4.0.5 on 2022-07-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_room2_course_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room2',
            name='course_codes',
        ),
        migrations.AddField(
            model_name='room2',
            name='course_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='room2',
            name='username',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
