# Generated by Django 4.0.5 on 2022-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_room2_course_codes_room2_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=8)),
                ('course_code', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Room2',
        ),
    ]
