# Generated by Django 4.0.5 on 2022-07-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_username_user_name_coursecode_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecode',
            name='class_abr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='class_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='class_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='class_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='enrolled',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='instructors',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='max_capacity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='requested',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='reserved_new',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='units',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coursecode',
            name='waitlisted',
            field=models.CharField(default='', max_length=100),
        ),
    ]
